#!/bin/bash

# In order to cross-compile node for Android using NDK, run:
#   source android-configure <path_to_ndk> [arch]
#
# By running android-configure with source, will allow environment variables to
# be persistent in current session. This is useful for installing native node
# modules with npm. Also, don't forget to set the arch in npm config using
# 'npm config set arch=<arch>'


if [ -z "$2" ]; then
    ARCH=arm
else
    ARCH="$2"
fi

API="14"
CC_VER="4.9"
case $ARCH in
    arm)
        DEST_CPU="$ARCH"
        SUFFIX="arm-linux-androideabi"
        TOOLCHAIN_NAME="$SUFFIX"
        ;;
    arm64)
        DEST_CPU="arm64"
        SUFFIX="aarch64-linux-android"
        TOOLCHAIN_NAME="$SUFFIX"
        API="21"
        ;;
    mips)
      DEST_CPU="mips"
      SUFFIX="mipsel-linux-android"
      TOOLCHAIN_NAME="$SUFFIX"
      ;;
    mips64)
      DEST_CPU="mips64"
      SUFFIX="mips64el-linux-android"
      TOOLCHAIN_NAME="$SUFFIX"
     ;;
    x86)
        DEST_CPU="ia32"
        SUFFIX="i686-linux-android"
        TOOLCHAIN_NAME="$ARCH"
        ;;
    x86_64)
        DEST_CPU="x64"
        SUFFIX="x86_64-linux-android"
        TOOLCHAIN_NAME="$ARCH"
        API="21"
        ;;
    *)
        echo "Unsupported architecture provided: $ARCH"
        exit 1
        ;;
esac

export TOOLCHAIN=$PWD/android-toolchain
mkdir -p $TOOLCHAIN
# $1/build/tools/make-standalone-toolchain.sh \
#     --toolchain=$TOOLCHAIN_NAME-$CC_VER \
#     --arch=$ARCH \
#     --install-dir=$TOOLCHAIN \
#     --platform=android-21
$1/build/tools/make_standalone_toolchain.py \
    --force \
    --arch=$ARCH \
    --install-dir=$TOOLCHAIN \
    --api=${API}
export PATH=$TOOLCHAIN/bin:$PATH
export AR=$TOOLCHAIN/bin/$SUFFIX-ar
export CC=$TOOLCHAIN/bin/$SUFFIX-gcc
export CXX=$TOOLCHAIN/bin/$SUFFIX-g++
export LINK=$TOOLCHAIN/bin/$SUFFIX-g++

GYP_DEFINES="target_arch=$ARCH"
GYP_DEFINES+=" v8_target_arch=$ARCH"
GYP_DEFINES+=" android_target_arch=$ARCH"
GYP_DEFINES+=" host_os=linux OS=android"
export GYP_DEFINES

if [ -f "configure" ]; then
    ./configure \
        --dest-cpu=$DEST_CPU \
        --dest-os=android \
        --without-snapshot \
        --openssl-no-asm \
	     --enable-static \
 	     --without-intl
fi
